// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListAIModels(arg1:main.TranslateRequest):Promise<main.ModelsResponse>;

export function TestAIAPI(arg1:main.TranslateRequest):Promise<main.TestResponse>;

export function TranslateMeasureNames(arg1:main.TranslateRequest):Promise<main.TranslateResponse>;
