// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAIModels(arg1) {
  return window['go']['main']['App']['ListAIModels'](arg1);
}

export function TestAIAPI(arg1) {
  return window['go']['main']['App']['TestAIAPI'](arg1);
}

export function TranslateMeasureNames(arg1) {
  return window['go']['main']['App']['TranslateMeasureNames'](arg1);
}
